FROM python:3.11.4-slim-bookworm

WORKDIR /app/

COPY ./requirements.txt /app/requirements.txt
RUN apt update && apt install -y adb
RUN pip install --no-cache-dir --upgrade -r /app/requirements.txt

COPY ./app /app