FROM tiangolo/uvicorn-gunicorn-fastapi:python3.11-2023-08-07

# WORKDIR /app/

# COPY ./requirements.txt /app/requirements.txt

# RUN pip install --no-cache-dir --upgrade -r /app/requirements.txt

COPY ./app /app