FROM node:lts-alpine3.14 as builder

WORKDIR /usr/src/app
ENV PATH "/usr/src/app/node_modules/.bin:${PATH}"

COPY package.json /usr/src/app/package.json
RUN npm install
COPY . /usr/src/app/


RUN npm run build:dev

FROM nginx:1.22.1-alpine

COPY nginx.conf /etc/nginx/conf.d/default.conf
COPY --from=builder /usr/src/app/dist/ /usr/share/nginx/html

CMD ["nginx", "-g", "daemon off;"]