version: "3.8"

services:
  backend:
    container_name: backend
    image: registry.dev-nextlab.com/prep-exec-analysis-backend:dev-0
    build:
      context: ./backend
      dockerfile: dockerfile.dev
    command: /start-reload.sh
    ports:
      - 5000:80
    volumes:
      - ./backend/app:/app

  mongodb:
    container_name: mongodb
    image: mongo:4.4.2
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: .nextlab6318!
    volumes:
      - mongodb_data:/data/db

  adminer:
    container_name: adminer
    image: dockette/adminer:full
    ports:
      - 8082:80

  redis:
    container_name: redis
    image: redis:7.0.4
    ports:
      - 6379:6379
    volumes:
      - redis_data:/data

  redis-commander:
    container_name: redis-commander
    image: rediscommander/redis-commander:latest
    environment:
    - REDIS_HOSTS=local:redis:6379
    ports:
    - 8081:8081

  stb-log:
    container_name: stb-log
    image: registry.dev-nextlab.com/prep-exec-analysis-stblog:dev-0
    build:
      context: ./stb_log
      dockerfile: Dockerfile
    command: python -u main.py

volumes:
  mongodb_data: {}
  redis_data: {}
