FROM tiangolo/uvicorn-gunicorn-fastapi:python3.9-slim-2021-10-02

WORKDIR /app/
RUN apt-get -y update
RUN apt-get -y upgrade
RUN apt-get install -y vim

COPY requirements.txt ./
RUN pip install pip --upgrade
RUN pip install --default-timeout 1000 -r requirements.txt

ENV SENTRY_DSN ''
ENV BACKEND_CORS_ORIGINS http://localhost:3000
ENV SERVICE_NAME prep-exec-analysis
ENV FILES_PATH /app/app/files
ENV REMOCON_COMPANY Vodafone,LG,KT

ENV MONGODB_SERVER mongodb
ENV MONGODB_NAME prep-exec-analysis
ENV MONGODB_PORT 27017
ENV MONGODB_USERNAME admin
ENV MONGODB_PASSWORD .nextlab6318!
ENV MONGODB_AUTHENTICATION_SOURCE admin

ENV REDIS_HOST redis
ENV REDIS_PORT 6379
ENV REDIS_DB 0

COPY ./app /app
ENV PYTHONPATH /app