FROM python:3.9.7
ARG DEBIAN_FRONTEND=noninteractive

# install fundamental
RUN apt-get update
RUN apt-get update && apt-get -y install libgl1-mesa-glx x264 libx264-dev libavcodec-dev

# install pip & python
RUN ln -s /usr/bin/python3 /usr/bin/python
RUN ln -s /usr/bin/pip3 /usr/bin/pip
RUN pip install --upgrade pip

# install requirements
WORKDIR /app/
ADD requirements.txt ./
RUN pip install -r requirements.txt

ADD . ./

ENV MONGODB_SERVER mongodb
ENV MONGODB_NAME prep-exec-analysis
ENV MONGODB_PORT 27017
ENV MONGODB_USERNAME admin
ENV MONGODB_PASSWORD .nextlab6318!
ENV MONGODB_AUTHENTICATION_SOURCE admin

ENV REDIS_HOST redis
ENV REDIS_PORT 6379
ENV REDIS_DB 0
ENV REDIS_PASSWORD ""

ENV TF_MODEL_URL https://drive.google.com/drive/folders/13tVYiXNTXeVjUdNtShxKGcUi2hgzZ9-Y?usp=share_link

# docker-compose up -d --build --force-recreate freeze resume boot log-pattern color-reference macroblock channel-zapping && docker-compose logs -f freeze resume boot log-pattern color-reference macroblock channel-zapping