FROM python:3.9.7
ARG DEBIAN_FRONTEND=noninteractive

# install fundamental
RUN apt-get update && \
    apt-get -y install libgl1-mesa-glx x264 libx264-dev libavcodec-dev

# install pip & python
RUN ln -s /usr/bin/python3 /usr/bin/python
RUN ln -s /usr/bin/pip3 /usr/bin/pip
RUN pip install --upgrade pip

# install requirements
ARG REQUIREMENTS=requirements.txt
WORKDIR /app/
ADD ${REQUIREMENTS} ./
RUN pip install -r ${REQUIREMENTS}

ADD . ./

ENV MONGODB_SERVER mongodb
ENV MONGODB_NAME prep-exec-analysis
ENV MONGODB_PORT 27017
ENV MONGODB_USERNAME admin
ENV MONGODB_PASSWORD .nextlab6318!
ENV MONGODB_AUTHENTICATION_SOURCE admin

ENV REDIS_HOST redis
ENV REDIS_PORT 6379
ENV REDIS_DB 0
ENV REDIS_PASSWORD ""

# docker-compose up -d --build freeze resume boot log-pattern color-reference && docker-compose logs -f freeze resume boot log-pattern color-reference
# docker-compose up -d --build macroblock && docker-compose logs -f macroblock
# docker-compose up -d --build channel-zapping && docker-compose logs -f channel-zapping
