FROM python:3.10.6
ARG DEBIAN_FRONTEND=noninteractive

# install fundamental
RUN apt update 
RUN apt install lsof net-tools tcpdump tshark ethtool traceroute iperf3 -y 

# install pip & python
RUN ln -s /usr/bin/python3 /usr/bin/python
RUN ln -s /usr/bin/pip3 /usr/bin/pip
RUN pip install --upgrade pip

# install requirements
WORKDIR /app/
ADD requirements.txt ./
RUN pip install -r requirements.txt

ENV REDIS_HOST redis
ENV REDIS_PORT 6379
ENV REDIS_DB 0
ENV REDIS_PASSWORD 66b44dcb7f981904f8536b19e4464725

ADD . ./

CMD ["python", "main.py"]