"""First revision

Revision ID: 4d53a951404a
Revises: 
Create Date: 2023-07-17 02:31:23.231602

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = '4d53a951404a'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
                    sa.Column('id', sa.Integer(),
                              nullable=False, comment='아이디'),
                    sa.Column('user_id', sa.String(length=10),
                              nullable=False, comment='사용자 아이디'),
                    sa.Column('password', sa.String(length=100),
                              nullable=False, comment='비밀번호'),
                    sa.Column('updated_at', sa.DateTime(timezone=True),
                              nullable=False, comment='변경일시'),
                    sa.PrimaryKeyConstraint('id'),
                    sa.UniqueConstraint('user_id')
                    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user')
    # ### end Alembic commands ###
