name: qaas-dev-m32dev4-frontend
run-name: ${{ github.actor }} is deploy qaas-dev-m32dev4-frontend
on: push
# on: workflow_dispatch
jobs:
  build-dev-m32dev4-frontend:
    runs-on: [self-hosted, docker, Linux]
    steps:
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: registry.dev-nextlab.com
          username: nextlab
          password: .nextlab1@
      - uses: actions/checkout@v3  
        with:
            submodules: recursive
      - run: docker build -t registry.dev-nextlab.com/qaas-frontend:dev-${{github.run_id}}${{github.run_number}} -f ./frontend/dockerfile.development ./frontend
        shell: bash
      - run: docker image push registry.dev-nextlab.com/qaas-frontend:dev-${{github.run_id}}${{github.run_number}}
        shell: bash

  deploy-dev-m32dev4-frontend:
    needs: [build-dev-m32dev4-frontend]
    runs-on: [self-hosted, qaas_m32dev4]
    steps:
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: registry.dev-nextlab.com
          username: nextlab
          password: .nextlab1@
      - run: docker image pull registry.dev-nextlab.com/qaas-frontend:dev-${{github.run_id}}${{github.run_number}}
        shell: bash
      - run: sed -i "s|\b/qaas-frontend:dev-.*\b|/qaas-frontend:dev-${{github.run_id}}${{github.run_number}}|g" /home/jade-m32-07/service/frontend.yml
        shell: bash
      - run: docker-compose --project-directory /home/jade-m32-07/service -f /home/jade-m32-07/service/frontend.yml up -d
        shell: bash
    # - run: docker stack deploy -c /home/nextlab/frontend_admin_heliodor/heliodor.yml heliodor-admin
