name: qaas-dev-frontend
run-name: ${{ github.actor }} is deploy qaas-dev-frontend
# on: push
on: workflow_dispatch
jobs:
  build-dev-frontend:
    runs-on: [self-hosted, ndev8]
    steps:
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: registry.dev-nextlab.com
          username: nextlab
          password: .nextlab1@
      - uses: actions/checkout@v3  
        with:
            submodules: recursive
      - run: docker build -t registry.dev-nextlab.com/qaas-frontend:dev-${{github.run_id}}${{github.run_number}} -f ./frontend/dockerfile.development ./frontend
        shell: bash
      - run: docker image push registry.dev-nextlab.com/qaas-frontend:dev-${{github.run_id}}${{github.run_number}}
        shell: bash

  deploy-dev-frontend:
    needs: [build-dev-frontend]
    runs-on: [self-hosted, ndev8]
    steps:
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: registry.dev-nextlab.com
          username: nextlab
          password: .nextlab1@
      - run: docker image pull registry.dev-nextlab.com/qaas-frontend:dev-${{github.run_id}}${{github.run_number}}
        shell: bash
      - run: sed -i "s|\b/qaas-frontend:dev-.*\b|/qaas-frontend:dev-${{github.run_id}}${{github.run_number}}|g" /home/svc/service/qaas/frontend.yml
        shell: bash
      - run: docker compose --project-directory /home/svc/service/qaas -f /home/svc/service/qaas/frontend.yml up -d
        shell: bash
    # - run: docker stack deploy -c /home/nextlab/frontend_admin_heliodor/heliodor.yml heliodor-admin