name: qaas-dev-test
run-name: ${{ github.actor }} is qaas-pre-test
on: push
jobs:
    build-test-backend:
        runs-on: [self-hosted, docker, Linux]
        steps:
          - run: docker build -t registry.dev-nextlab.com/qaas-backend:dev-${{github.run_id}}${{github.run_number}} -f ./backend/dockerfile.dev.m32dev4 ./backend
            shell: bash
    build-test-frontend:
        runs-on: [self-hosted, docker, Linux]
        steps:
          - run: docker build -t registry.dev-nextlab.com/qaas-frontend:dev-${{github.run_id}}${{github.run_number}} -f ./frontend/dockerfile.development ./frontend
            shell: bash
    build-test-media:
        runs-on: [self-hosted, docker, Linux]
        steps:
          - run: docker build -t registry.dev-nextlab.com/qaas-media:dev-${{github.run_id}}${{github.run_number}} -f ./media/dockerfile.dev.m32dev4 ./media
            shell: bash
    build-dev-m32dev4-stblog:
        runs-on: [self-hosted, docker, Linux]
        steps:
          - run: docker build -t registry.dev-nextlab.com/qaas-stblog:dev-${{github.run_id}}${{github.run_number}} -f ./stb_log/Dockerfile ./stb_log
            shell: bash